# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pals', '0002_auto_20161106_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
