# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pals', '0003_userprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='imageUrl',
            field=models.URLField(default='none', max_length=500),
        ),
    ]
