# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pals', '0004_userprofile_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(default='none', max_length=5000),
        ),
    ]
